# Generated by Django 5.1.7 on 2025-07-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mfd', models.DateField()),
                ('exp', models.DateField()),
                ('purchase_date', models.DateField()),
            ],
        ),
    ]
